title: John Vusich's Blog
description: Welcome to my personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnvusich.github.io" # the base hostname & protocol for your site
theme: minima # you can choose any Jekyll theme you like
